services:
  - type: web
    name: am-maturity-survey
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    autoDeploy: true
    envVars:
      - key: GH_REPO
        value: "owner/repo"   # مثلا seyedipour/asset-management-maturity
      - key: GH_BRANCH
        value: "main"
      - key: GH_DIR
        value: "data"
      # توکن رو در داشبورد Render به صورت Secret بذار (نه در فایل)
